### ISSUE TITLE
"Unknown error occurred" when setting up

### ISSUE THREAD

**Issue by kawlsson** [toringer/home-assistant-heru#14]
## Version of the custom_component

Version 0.3.0

## Configuration
HA details:
 Home Assistant 2023.6.1 Supervisor 2023.06.1 Operating System 10.2 Frontend 20230608.0 - latest 

## Describe the bug
Trying to replace my yaml modbus config that works but when setting up the integration i get a unknown error.
It worked fine with the yaml so shouldnt be any communication issues etc.
Completely removed the yaml code.

## Debug log

```text

Logger: aiohttp.server
Source: custom_components/heru/helpers/config_flow.py:30
Integration: HERU ([documentation](https://github.com/toringer/home-assistant-heru/), [issues](https://github.com/toringer/home-assistant-heru/issues))
First occurred: 10:30:02 (2 occurrences)
Last logged: 10:32:23
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heru/config_flow.py", line 52, in async_step_user
    error = await FlowValidator.validate_step_user(self.hass, user_input)
            ^^^^^^^^^^^^^^^
![heru_ha](https://github.com/toringer/home-assistant-heru/assets/67454783/addbeb63-f9c0-432e-bf68-69f14b9b3ac6)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heru/helpers/config_flow.py", line 30, in validate_step_user
    old_client = hass.data[DOMAIN]["client"]
                 ~~~~~~~~~^^^^^^^^
KeyError: 'heru'

```
![heru_ha](https://github.com/toringer/home-assistant-heru/assets/67454783/1d5eebef-673c-4710-910d-230c7515d0a8)

**Comment by toringer** [comment]
Currently refactoring the component. I then found another error that might be related. Please hold on for the new version, and then try again.

**Comment by toringer** [comment]
@kawlsson, I just released a new version. It should be working now.

**Comment by kawlsson** [comment]
@toringer Thank you!, it works perfectly now.

**Comment by eklofmar** [comment]
@toringer After updateing to the latest version (1.00), I get the same error. It was not there before updateing.

**Comment by eklofmar** [comment]
> @eklofmar Please add full error log.

`Logger: aiohttp.server
Source: custom_components/heru/helpers/config_flow.py:32
Integration: HERU ([documentation](https://github.com/toringer/home-assistant-heru/), [issues](https://github.com/toringer/home-assistant-heru/issues))
First occurred: 20:49:42 (1 occurrences)
Last logged: 20:49:42

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 242, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heru/config_flow.py", line 95, in async_step_init
    error = await FlowValidator.validate_step_user(self.hass, user_input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heru/helpers/config_flow.py", line 32, in validate_step_user
    coordinator = hass.data[DOMAIN]["coordinator"]
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'coordinator'`


![image](https://github.com/toringer/home-assistant-heru/assets/102030195/de392058-9578-4812-bb14-cbbd4aaca171)

**Comment by toringer** [comment]
Thanks. What exactly are you doing? Are you 
- adding the device to a "clean" system (no existing HERU device on the system)
- Trying to reconfigure the device

**Comment by eklofmar** [comment]
> @eklofmar please try the new version v1.0.1

Thank you! Now it is working!
