### ISSUE TITLE
Only 7 entities

### ISSUE THREAD

**Issue by borut-s** [toringer/home-assistant-heru#16]
## Version of the custom_component
Version 1.0.1
## Configuration
New instalation on new HACS. I have Heru 100 T EC. I connect it to the router via integrated LAN port, enable modbus TCP/IP with port 502, instal HACS and add Heru integration wich works partly.

## Describe the bug
I have only 7 entities: 

1. Clear Alarms,
2. Comfort 
3. Night cooling exhaust high limit, 
4. Night cooling exhaust low limit, 
5. Night cooling indoor-outdoor diff. limit, 
6. Reset filter timer, 
7. Sync date and time. 

Debug log show 2 following errors. Did I do anything wrong or there is a problem in code?

## Debug log
Logger: homeassistant.components.switch
Source: custom_components/heru/switch.py:47
Integration: Stikalo (documentation, issues)
First occurred: 15:32:47 (1 occurrences)
Last logged: 15:32:47

Error while setting up heru platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/heru/switch.py", line 29, in async_setup_entry
    switches.append(HeruSwitch(coordinator, switch, entry))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heru/switch.py", line 42, in __init__
    self._attr_is_on = self._get_value()
                       ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heru/switch.py", line 47, in _get_value
    return self.coordinator.coils[self.idx["address"]]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range


Logger: homeassistant.components.sensor
Source: custom_components/heru/sensor.py:60
Integration: Senzor (documentation, issues)
First occurred: 15:32:47 (1 occurrences)
Last logged: 15:32:47

Error while setting up heru platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/heru/sensor.py", line 31, in async_setup_entry
    sensors.append(HeruSensor(coordinator, sensor, entry))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heru/sensor.py", line 50, in __init__
    self._attr_native_value = self._get_value()
                              ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heru/sensor.py", line 60, in _get_value
    value = self.coordinator.discrete_inputs[self.idx["address"]]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
![Heru](https://github.com/toringer/home-assistant-heru/assets/76726402/e1c8c516-da67-4088-90ef-7e793b95b0f9)

**Comment by borut-s** [comment]
I update Heru to 1.10, restart Home Assistant and now is working. Thanks anyway.
